// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMded3-zC6r4J91ACn0gkUMlB6grCz_MQ',
    appId: '1:301732570592:android:fa101e491a42ad23bcf785',
    messagingSenderId: '301732570592',
    projectId: 'firstaidapp1-811e3',
    databaseURL: 'https://firstaidapp1-811e3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firstaidapp1-811e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDYGXs4rXr7dyGmOLZeRTS6os09CnX3Q',
    appId: '1:301732570592:ios:9b1e3b43c12095edbcf785',
    messagingSenderId: '301732570592',
    projectId: 'firstaidapp1-811e3',
    databaseURL: 'https://firstaidapp1-811e3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firstaidapp1-811e3.firebasestorage.app',
    androidClientId: '301732570592-39pqt1lufiuj8crpm6opm7afoiqui5vi.apps.googleusercontent.com',
    iosClientId: '301732570592-074uuee6sdig4ukrb4fs03hnd26ufaoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstAidApp',
  );

}